Models/bind.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using jobshow.Models;
using System.Data.Entity;

namespace jobshow.Models
{
    public class bind :DbContext
    {
        public bind()
        {

        }

        public DbSet<job> job { get; set; }
        public DbSet<company> company { get; set; }
    }
}

Models/company.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;


namespace jobshow.Models
{
    public class company
    {
        //companyid
        [Key]
        public int companyId { get; set; }

        //companyname
        public string companyName { get; set; }

        //owner
        public string companyownerName { get; set; }

        //company type
        public string companyType { get; set; }


    }
}

Models/job.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace jobshow.Models
{
    public class job
    {
        //job id
        [Key]
        public int jobId { get; set; }

        //companyname
        public string jobName { get; set; }

        //owner
        public string jobDetails { get; set; }

        //company type
        public string jobRequirement { get; set; }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace jobshow.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/companyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using jobshow.Models;
using System.Net;

namespace jobshow.Controllers
{
    public class companyController : Controller
    {
        private bind db = new bind();

        public ActionResult List()
        {
            return View(db.company.ToList());
        }


        //GET: Details of company
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            company com = db.company.Find(id);
            if (com == null)
            {
                return HttpNotFound();
            }
            return View(com);
        }

        // GET:  create company
        public ActionResult Create()
        {
            return View();
        }
        //POST: Save new company
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "companyId,companyName,companyownerName,companyType")] company comp)
        {
            if (ModelState.IsValid)
            {
                db.company.Add(comp);
                db.SaveChanges();
                return RedirectToAction("List");
            }
            return View(comp);
        }

        //GET: Edit company
        public ActionResult edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            company com = db.company.Find(id);
            if (com == null)
            {
                return HttpNotFound();
            }
            return View(com);
        }
        //POST: Edit company

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult edit([Bind(Include = "companyId,companyName,companyownerName,companyType")] company com)
        {
            if (ModelState.IsValid)
            {
                db.Entry(com).State = EntityState.Modified;
                db.SaveChanges();
              return RedirectToAction("List");
            }
            return View(com);
        }



        //GET: Delete of company
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            company com = db.company.Find(id);
            if (com == null)
            {
                return HttpNotFound();
            }
            return View(com);
        }
        //POST : delete
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            company com = db.company.Find(id);
            db.company.Remove(com);
            db.SaveChanges();
            return RedirectToAction("List");
            //return View();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



    }
}

Controllers/jobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using jobshow.Models;
using System.Net;



namespace jobshow.Controllers
{
    public class jobController : Controller
    {
        private bind db = new bind();
        // GET: job
        public ActionResult List()
        {
            return View(db.job.ToList());
        }

        //GET: Details of job
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            job j = db.job.Find(id);
            if (j == null)
            {
                return HttpNotFound();
            }
            return View(j);
        }

        // GET:  create job
        public ActionResult Create()
        {
            return View();
        }
        //POST: Save new job
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "jobId,jobName,jobDetails,jobRequirement")] job j)
        {
            if (ModelState.IsValid)
            {
                db.job.Add(j);
                db.SaveChanges();
                return RedirectToAction("List");
            }
            return View(j);
        }

        //GET: Edit job
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            job j = db.job.Find(id);
            if (j == null)
            {
                return HttpNotFound();
            }
            return View(j);
        }
        //POST: Edit job

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "jobId,jobName,jobDetails,jobRequirement")] job j)
        {
            if (ModelState.IsValid)
            {
                db.Entry(j).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("List");
            }
            return View(j);
        }



        //GET: Delete of job
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            job j = db.job.Find(id);
            if (j == null)
            {
                return HttpNotFound();
            }
            return View(j);
        }
        //POST : delete
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            job j = db.job.Find(id);
            db.job.Remove(j);
            db.SaveChanges();
            return RedirectToAction("List");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }











    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Company", "List", "company")</li>
                    <li>@Html.ActionLink("Job", "List", "job")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/company/Create.cshtml
@model jobshow.Models.company

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>company</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.companyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.companyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.companyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.companyownerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.companyownerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.companyownerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.companyType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.companyType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.companyType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "list")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/company/Delete.cshtml
@model jobshow.Models.company

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>company</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.companyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.companyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.companyownerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.companyownerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.companyType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.companyType)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "list")
        </div>
    }
</div>

Views/company/Details.cshtml
@model jobshow.Models.company

@{
    ViewBag.Title = "Details";
}

<h2>Deatils</h2>

<div>
    <h4>company</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.companyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.companyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.companyownerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.companyownerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.companyType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.companyType)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.companyId }) |
    @Html.ActionLink("Back to List", "list")
</p>

Views/company/edit.cshtml
@model jobshow.Models.company

@{
    ViewBag.Title = "edit";
}

<h2>edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>company</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.companyId)

        <div class="form-group">
            @Html.LabelFor(model => model.companyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.companyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.companyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.companyownerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.companyownerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.companyownerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.companyType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.companyType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.companyType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "list")
</div>

Views/company/list.cshtml
@model IEnumerable<jobshow.Models.company>

@{
    ViewBag.Title = "list";
}

<h2>list</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.companyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.companyownerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.companyType)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.companyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.companyownerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.companyType)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.companyId }) |
            @Html.ActionLink("Details", "Details", new { id=item.companyId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.companyId })
        </td>
    </tr>
}

</table>

Views/job/Create.cshtml
@model jobshow.Models.job

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>job</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.jobName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.jobName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.jobName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.jobDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.jobDetails, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.jobDetails, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.jobRequirement, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.jobRequirement, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.jobRequirement, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

Views/job/Delete.cshtml
@model jobshow.Models.job

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>job</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.jobName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.jobName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.jobDetails)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.jobDetails)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.jobRequirement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.jobRequirement)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "List")
        </div>
    }
</div>

Views/job/Details.cshtml
@model jobshow.Models.job

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>job</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.jobName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.jobName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.jobDetails)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.jobDetails)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.jobRequirement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.jobRequirement)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.jobId }) |
    @Html.ActionLink("Back to List", "List")
</p>

Views/job/Edit.cshtml
@model jobshow.Models.job

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>job</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.jobId)

        <div class="form-group">
            @Html.LabelFor(model => model.jobName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.jobName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.jobName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.jobDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.jobDetails, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.jobDetails, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.jobRequirement, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.jobRequirement, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.jobRequirement, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

Views/job/List.cshtml
@model IEnumerable<jobshow.Models.job>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.jobName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.jobDetails)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.jobRequirement)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.jobName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.jobDetails)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.jobRequirement)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.jobId }) |
            @Html.ActionLink("Details", "Details", new { id=item.jobId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.jobId })
        </td>
    </tr>
}

</table>